name: Trigger auto deployment for capp-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-demo-AutoDeployTrigger-e49e0d34-923e-48bf-83cb-f3d107612a56.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caadef8f9052acr.azurecr.io
          username: ${{ secrets.CAPPDEMO_REGISTRY_USERNAME }}
          password: ${{ secrets.CAPPDEMO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caadef8f9052acr.azurecr.io/capp-demo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPDEMO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n capp-demo -g happyhour-demo --server caadef8f9052acr.azurecr.io --username  ${{ secrets.CAPPDEMO_REGISTRY_USERNAME }} --password ${{ secrets.CAPPDEMO_REGISTRY_PASSWORD }}
            az containerapp update -n capp-demo -g happyhour-demo --image caadef8f9052acr.azurecr.io/capp-demo:${{ github.sha }}
